// Generated by CoffeeScript 1.7.1
(function() {
  this.ChatWindow = (function() {
    function ChatWindow() {
      this.unreadCount = 0;
      this.$chatWindow = $('#chat');
      window.onbeforeunload = function(e) {
        var msg, msg_obj;
        msg_obj = new EventMessage('Bye bye...');
        msg = {
          type: 'EVENT',
          event: 'SIGN_OFF',
          username: username
        };
        ws.send(JSON.stringify(msg));
        ws.close(1000, username + " left the chat..");
        if (!e) {
          e = window.event;
        }
        e.stopPropagation();
        return e.preventDefault();
      };
      window.onmousemove = (function(_this) {
        return function(e) {
          return _this._resetUnreadCount();
        };
      })(this);
      $('#message').keypress((function(_this) {
        return function(e) {
          return _this._resetUnreadCount();
        };
      })(this));
    }

    ChatWindow.prototype._resetUnreadCount = function() {
      this.unreadCount = 0;
      return this._updateTitle();
    };

    ChatWindow.prototype._updateTitle = function() {
      var title;
      title = "MockingJay";
      if (this.unreadCount > 0) {
        title = "(" + this.unreadCount + ") " + title;
      }
      return document.title = title;
    };

    ChatWindow.prototype._autoScroll = function() {
      return $(window).scrollTop($(window).height());
    };

    ChatWindow.prototype.update = function() {
      this._updateTitle();
      this._autoScroll();
      if (this.$chatWindow.children().length > 200) {
        this.$chatWindow.children()[0].remove();
        return this.$chatWindow.children()[1].remove();
      }
    };

    ChatWindow.prototype.append = function(msg) {
      var $msg;
      if (!msg) {
        return;
      }
      this.unreadCount++;
      $msg = msg.say();
      if ((this.$chatWindow.children().length % 2) === 1) {
        $msg.addClass('uc-odd');
      }
      if ($msg.val().indexOf(username) !== -1) {
        chime.play();
        $msg.addClass('highlight');
      }
      this.$chatWindow.append($msg);
      return this.update();
    };

    return ChatWindow;

  })();

}).call(this);
